### ISSUE TITLE
Is it correct syntax in the last 5 lines?

### ISSUE THREAD

**Issue by litvinen** [StochasticNumerics/mimclib#16]
try:
    # Try to import the DLL version of wcumsum,
    # This makes solving the SDE much faster
    import ctypes as ct
    import numpy.ctypeslib as npct
    __arr_double__ = npct.ndpointer(dtype=np.double, flags='C_CONTIGUOUS')
    __libdir = os.path.join(os.path.dirname(__file__))
    __lib__ = npct.load_library("needed_functions.so", __libdir)
    __lib__.my_init.restype = None
    __lib__.my_init.argtypes = None #[ct.c_uint32, ct.c_uint32]
    __lib__.LvlSample.restype = None
    __lib__.LvlSample.argtypes = [ct.c_uint32,ct.c_uint32,ct.c_uint32, __arr_double__, __arr_double__]

    def my_init(argc0, argv0):
        
        __lib__.my_init()
        return s0

    def LvlSample(Nc, Nf, M):
	
        s1= np.zeros(1)
        s2= np.zeros(1)
        __lib__.LvlSample(Nc, Nf, M, s1, s2)
	return s1[1], s2[1]

**Comment by Virtakuono** [comment]
I'm not purely sure on which lines you are concerned about but if you are concerned about syntax, put it in an interpreter and try out?

**Comment by litvinen** [comment]
Sorry, the error was in 
return s1[0], s2[0]
I forgot that in python it is like in c, starting from zero.
