### ISSUE TITLE
Sub-optimal error handling

### ISSUE THREAD

**Issue by Virtakuono** [StochasticNumerics/mimclib#21]
I find the following a bit silly:

https://github.com/StochasticNumerics/mimclib/blob/eb908a7b02777f4e7d5c2d29a465d2e7948054a8/tests/gbm/run.py#L63

The try can fail for two different reasons:
1. mimcRun.doRun() raises an exception
2. db.markRunDone(run_id) raises an exception

In the latter case, the code tries again to save a successful run into a database as an unsuccessful one, just because there is a glitch with the database.

**Comment by haji-ali** [comment]
Fair, fixed in a922c38f9fe648c2e754eb378a4732de2a094680
If you pull the changes please execute the following in your DB

`ALTER TABLE tbl_runs ADD comment TEXT;`
