### ISSUE TITLE
Problem with run.py

### ISSUE THREAD

**Issue by litvinen** [StochasticNumerics/mimclib#23]
kw13919:litvina~/MIMCLIB/mimclib/tests/CEM> ./echo_test_cmd_alex.py -multi True | parallel -j 5
Traceback (most recent call last):
  File "run.py", line 131, in <module>
    main()
  File "run.py", line 67, in main
    db.markRunDone(run_id)
TypeError: markRunDone() takes exactly 3 arguments (2 given)
Traceback (most recent call last):
  File "run.py", line 131, in <module>
    main()
  File "run.py", line 67, in main
    db.markRunDone(run_id)
TypeError: markRunDone() takes exactly 3 arguments (2 given)

**Comment by haji-ali** [comment]
Change your code in `run.py` so that it is exactly like here
https://github.com/StochasticNumerics/mimclib/blob/master/tests/gbm/run.py#L63-L72

BTW, you can use code tags while posting a question.

**Comment by haji-ali** [comment]
Actually, I decided to make things a bit easier for our tests. Check the new 
https://github.com/StochasticNumerics/mimclib/blob/37b3ca940d2878dbe1d0712334ae521c9ba2b684/tests/gbm/run.py#L71-L73

Not sure if I will keep it like this, but for now the solution is elegant.
