### ISSUE TITLE
How to see log files with all convergences, parameters etc?

### ISSUE THREAD

**Issue by litvinen** [StochasticNumerics/mimclib#26]
How to see log files with all convergences, parameters etc? How to get them from DB?

**Comment by haji-ali** [comment]
You have to use
`db.readRuns()`
and `db.getRunIDs()`

see https://github.com/StochasticNumerics/mimclib/blob/ddf98c9e3b4e06100f92601faa8f65bbb3c66294/tests/plot_data.py#L50-L52

for an example

**Comment by litvinen** [comment]
Thanks
