### ISSUE TITLE
Would be nice to have list of 10 most used mysql commands

### ISSUE THREAD

**Issue by litvinen** [StochasticNumerics/mimclib#29]
It is not so problem in mysql syntax, but rather with too may information: There are 6 Tables, each contains 6-12 columns, some data are repeating. I have feeling that I use 1% of capabilities.

**Comment by Virtakuono** [comment]
Duplicate of https://github.com/StochasticNumerics/mimclib/issues/22 ?

**Comment by litvinen** [comment]
Yes, but 22 contains only a short example. Would be nice to see more options.

**Comment by Virtakuono** [comment]
That's why I said I'll leave the thread open. If you need something, you can expand the thread with your requests.

**Comment by litvinen** [comment]
Ok, thanks
