### ISSUE TITLE
Out of memory flag

### ISSUE THREAD

**Issue by litvinen** [StochasticNumerics/mimclib#30]
It would be nice to introduce a new parameter(warning or feature), which tells how much memory one will need (how much memory one needs on each level).
Possible input is parameter \beta0, where N^{\beta0} is matrix storage.
\beta0=1 for sparse , Toeplitz or 3/5/7 -diagonal matrices (Laplace equation) and \beta0=2 for dense matrices (e.g. covariance).
OUTPUT: maximum number of levels and how much memory is allocated on each level

**Comment by Virtakuono** [comment]
This depends on how many parallel threads you have, and the script, as I see it, has no control over that.
