### ISSUE TITLE
can't start parallel -j20  from remote machine

### ISSUE THREAD

**Issue by litvinen** [StochasticNumerics/mimclib#36]
I login to my office machine like
ssh -X loginname@...
Then I try to run in parallel 
kw13919:litvina~/MIMCLIB/mimclib/tests/CEM> ./echo_test_cmd_alex.py -mutli True | parallel -j20 > CEM_test18.txt

But if I see the number of active processes in TOP (via terminal command top), I see only one and not 20. Why?

**Comment by haji-ali** [comment]
`-multi True`
not
`-mutli True`
