### ISSUE TITLE
Do not see results in database

### ISSUE THREAD

**Issue by litvinen** [StochasticNumerics/mimclib#38]
It should be a lot of results with tag CEM_18, I computed them many days, was able to see intermediate results, but after last computations I obtain this
kw13919:litvina~/MIMCLIB/mimclib/tests> ./plot_data.py  -db_tag CEM_18 -o 15Apr_noise003.pdf
plot.py:25: (RuntimeWarning) divide by zero encountered in divide
kw13919:litvina~/MIMCLIB/mimclib/tests> 

Why it happen?

**Comment by litvinen** [comment]
and how to delete from the database all records which contain zero (plot.py:25) ?
It could be that I have 1000 good records and just one "bad" record with zero...

**Comment by haji-ali** [comment]
What do you expect to happen? This is a warning and I am not sure what causes it. I suspect that you can safely ignore it.


On Apr 16, 2016, 9:17 AM +0200, Alexander Litvinenko<notifications@github.com>, wrote:
>  
> and how to delete from the database all records which contain zero (plot.py:25) ?
> It could be that I have 1000 good records and just one "bad" record with zero...
>  
>  
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly orview it on GitHub(https://github.com/StochasticNumerics/mimclib/issues/38#issuecomment-210755021)
>  
>  
>  



-- 

------------------------------
This message and its contents, including attachments are intended solely 
for the original recipient. If you are not the intended recipient or have 
received this message in error, please notify me immediately and delete 
this message from your computer system. Any unauthorized use or 
distribution is prohibited. Please consider the environment before printing 
this email.

**Comment by litvinen** [comment]
Abdul, you are right, by some reason I thought this was an error message. I am able to generate plots and see them.
