### ISSUE TITLE
Error message  assert(np.all(moments == np.array([1,2]))) in run.py, Line 48

### ISSUE THREAD

**Issue by litvinen** [StochasticNumerics/mimclib#39]
kw13919:litvina~/MIMCLIB/mimclib/tests/CEM> ./echo_test_cmd_alex.py -multi True | parallel -j1 > CEM_test22.txt
test.py:19: (ArgumentWarning) Argument -qoi_sigma was not used!
test.py:19: (ArgumentWarning) Argument -qoi_mu was not used!
Traceback (most recent call last):
  File "run.py", line 68, in <module>
    fnSeed=seedRandomGen)
  File "/home/litvina/MIMCLIB/mimclib/mimclib/test.py", line 82, in RunStandardTest
    mimcRun.doRun()
  File "/home/litvina/MIMCLIB/mimclib/mimclib/mimc.py", line 600, in doRun
    newTodoM)), verbose)
  File "/home/litvina/MIMCLIB/mimclib/mimclib/mimc.py", line 535, in _genSamples
    self.data.M[i])
  File "/home/litvina/MIMCLIB/mimclib/mimclib/test.py", line 76, in <lambda>
    fnSampleLvl = lambda moments, mods, inds, M, fn=fnSampleLvl, *a: fn(mimcRun, moments, mods, inds, M)
  File "run.py", line 48, in mySampleLvl
    assert(np.all(moments == np.array([1,2])))
AssertionError
test.py:19: (ArgumentWarning) Argument -qoi_sigma was not used!
test.py:19: (ArgumentWarning) Argument -qoi_mu was not used!

**Comment by haji-ali** [comment]
As we talked about earlier. Your code is not general and that is why we added checks to make sure no more than 2 moments are computed. You will have to update your C code to generate an arbitrary number of moment code and then modify the python code accordingly. Pedro has a working example that you can get hints from.


On Apr 16, 2016, 11:00 AM +0200, Alexander Litvinenko<notifications@github.com>, wrote:
>  
> kw13919:litvina~/MIMCLIB/mimclib/tests/CEM>./echo_test_cmd_alex.py -multi True | parallel -j1>CEM_test22.txt
> test.py:19: (ArgumentWarning) Argument -qoi_sigma was not used!
> test.py:19: (ArgumentWarning) Argument -qoi_mu was not used!
> Traceback (most recent call last):
> File "run.py", line 68, in
> fnSeed=seedRandomGen)
> File "/home/litvina/MIMCLIB/mimclib/mimclib/test.py", line 82, in RunStandardTest
> mimcRun.doRun()
> File "/home/litvina/MIMCLIB/mimclib/mimclib/mimc.py", line 600, in doRun
> newTodoM)), verbose)
> File "/home/litvina/MIMCLIB/mimclib/mimclib/mimc.py", line 535, in _genSamples
> self.data.M[i])
> File "/home/litvina/MIMCLIB/mimclib/mimclib/test.py", line 76, in
> fnSampleLvl = lambda moments, mods, inds, M, fn=fnSampleLvl, *a: fn(mimcRun, moments, mods, inds, M)
> File "run.py", line 48, in mySampleLvl
> assert(np.all(moments == np.array([1,2])))
> AssertionError
> test.py:19: (ArgumentWarning) Argument -qoi_sigma was not used!
> test.py:19: (ArgumentWarning) Argument -qoi_mu was not used!
>  
>  
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly orview it on GitHub(https://github.com/StochasticNumerics/mimclib/issues/39)
>  
>  
>  



-- 

------------------------------
This message and its contents, including attachments are intended solely 
for the original recipient. If you are not the intended recipient or have 
received this message in error, please notify me immediately and delete 
this message from your computer system. Any unauthorized use or 
distribution is prohibited. Please consider the environment before printing 
this email.

**Comment by pvilanova** [comment]
Alex: 

As long as you can compute the quantity of interest for each realization, mimclib can build all the plots from it, because it only needs to compute the raw moments. That is, you need to be able to compute g(.), g(.)^2, g(.)^3 and so on (g(.) being the quantity of interest of each realization). 

Check 
http://mathworld.wolfram.com/RawMoment.html

**Comment by litvinen** [comment]
Thanks !
