### ISSUE TITLE
How to regenerate the database ?

### ISSUE THREAD

**Issue by litvinen** [StochasticNumerics/mimclib#40]
Assume the author changed the database structure. How to regenerate it?
What will happen with old data?

**Comment by haji-ali** [comment]
The old data will be deleted. I haven't changed the database in a while. If I think that there is a needed change I will send you the commands that do the change without removing the old data.


On Apr 16, 2016, 2:30 PM +0200, Alexander Litvinenko<notifications@github.com>, wrote:
>  
> Assume the author changed the database structure. How to regenerate it?
> What will happen with old data?
>  
>  
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly orview it on GitHub(https://github.com/StochasticNumerics/mimclib/issues/40)
>  
>  
>  



-- 

------------------------------
This message and its contents, including attachments are intended solely 
for the original recipient. If you are not the intended recipient or have 
received this message in error, please notify me immediately and delete 
this message from your computer system. Any unauthorized use or 
distribution is prohibited. Please consider the environment before printing 
this email.

**Comment by litvinen** [comment]
Thanks Abdul. Answer from Pedro:
As far as I remember first you should do (into mysql client)

drop database mimc;

and then run 
ipython -c "import mimclib.db; print mimclib.db.MIMCDatabase().DBCreationScript(True)" | mysql
