### ISSUE TITLE
Database error with the updated code

### ISSUE THREAD

**Issue by Virtakuono** [StochasticNumerics/mimclib#41]
I get a database error trying to run the GBM example as follows:
./echo_test_cmd.py -multi 1 |parallel -j 10

_mysql_exceptions.OperationalError: (1054, "Unknown column 'psums_delta' in 'field list'")

**Comment by haji-ali** [comment]
Please follow the instructions I sent in an email previously to update the database.

**Comment by Virtakuono** [comment]
Amazing, it did it, on second try. I could have guaranteed that I ran the command once already. Anyways. I'll include the cmd that did the job if someone faces the same issue again:

python -c 'from mimclib.db import MIMCDatabase ; \
print MIMCDatabase().DBCreationScript(True);' | mysql
