### ISSUE TITLE
Plotting routine error

### ISSUE THREAD

**Issue by Virtakuono** [StochasticNumerics/mimclib#42]
For some reason the plotting routine does not work for me.

Running the gbm example:
gbm -multi 1 |parallel -j 10

and then trying to plot:
./plot_data.py -db_tag GBM_test_kurtosis -o test.pdf

I get AttributeError: '_process_plot_var_args' object has no attribute 'prop_cycler'

**Comment by Virtakuono** [comment]
I am running the following command in the python prompt, and there indeed is no attribute prop_cycler, perhaps a particular version of matplotlib is needed...

dir(plt.figure().gca()._get_lines)

**Comment by haji-ali** [comment]
Can you check the version you have (for posterity) and then update it using pip?


On May 18, 2016, 6:06 PM +0300, Juho Häppölä<notifications@github.com>, wrote:
>  
> I am running the following command in the python prompt, and there indeed is no attribute prop_cycler, perhaps a particular version of matplotlib is needed...
>  
>  
> dir(plt.figure().gca()._get_lines)
>  
>  
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly orview it on GitHub(https://github.com/StochasticNumerics/mimclib/issues/42#issuecomment-220056305)
>  
>  
>  



-- 

------------------------------
This message and its contents, including attachments are intended solely 
for the original recipient. If you are not the intended recipient or have 
received this message in error, please notify me immediately and delete 
this message from your computer system. Any unauthorized use or 
distribution is prohibited. Please consider the environment before printing 
this email.

**Comment by Virtakuono** [comment]
I have matplotlib version 1.3.1, the most recent that ubuntu repositories gives. The package I get from pip does not even compile, but gives me
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-Yd7WqZ/matplotlib/

**Comment by haji-ali** [comment]
Yeah. That's the problem. I am assuming at least 1.5 (actually 'make pip' should be checking that requirement). I will check it for you later today.


On May 19, 2016, 9:23 AM +0300, Juho Häppölä<notifications@github.com>, wrote:
>  
> I have matplotlib version 1.3.1, the most recent that ubuntu repositories gives. The package I get from pip does not even compile, but gives me
> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-Yd7WqZ/matplotlib/
>  
>  
> —
> You are receiving this because you commented.
> Reply to this email directly orview it on GitHub(https://github.com/StochasticNumerics/mimclib/issues/42#issuecomment-220237884)
>  
>  
>  



-- 

------------------------------
This message and its contents, including attachments are intended solely 
for the original recipient. If you are not the intended recipient or have 
received this message in error, please notify me immediately and delete 
this message from your computer system. Any unauthorized use or 
distribution is prohibited. Please consider the environment before printing 
this email.

**Comment by Virtakuono** [comment]
It seems that the solution for this is indeed to update matplotlib into version 1.5 of later using pip.
