### ISSUE TITLE
stuff in ./build needed?

### ISSUE THREAD

**Issue by Virtakuono** [StochasticNumerics/mimclib#43]
I'm getting these notifications of untracked files present at /build, which, is kind of annoying. Can I add /build to .gitignore, contents of that folder should not be distributed, but compiled on each computer separately, right?

**Comment by haji-ali** [comment]
Yes, you may.

On Sun, May 22, 2016 at 9:29 AM, Juho Häppölä <notifications@github.com>
wrote:

> I'm getting these notifications of untracked files present at /build,
> which, is kind of annoying. Can I add /build to .gitignore, contents of
> that folder should not be distributed, but compiled on each computer
> separately, right?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/StochasticNumerics/mimclib/issues/43>
>

-- 

------------------------------
This message and its contents, including attachments are intended solely 
for the original recipient. If you are not the intended recipient or have 
received this message in error, please notify me immediately and delete 
this message from your computer system. Any unauthorized use or 
distribution is prohibited. Please consider the environment before printing 
this email.

**Comment by Virtakuono** [comment]
Done in 4e10934a56637f13827ff28b4a53737a200673a6
