### ISSUE TITLE
Implement a storing mechanism in files instead of database.

### ISSUE THREAD

**Issue by Virtakuono** [StochasticNumerics/mimclib#49]
From README

**Comment by litvinen** [comment]
I miss the option to see everything in a LOG file ( decay of EXP, decay of VAR etc). It would be nice to have both the LOG file and the database

**Comment by haji-ali** [comment]
You can have both by passing
-db True -verbose True
To your run.py file


On Jun 8, 2016, 9:26 PM +0200, Alexander Litvinenko<notifications@github.com>, wrote:
>  
> I miss the option to see everything in a LOG file ( decay of EXP, decay of VAR etc). It would be nice to have both the LOG file and the database
>  
>  
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly,view it on GitHub(https://github.com/StochasticNumerics/mimclib/issues/49#issuecomment-224700775), ormute the thread(https://github.com/notifications/unsubscribe/AQb4EIFHeGTbfV0DajEYN8RDqTHp5xi8ks5qJxd5gaJpZM4IkYpm).
>  
>  
>  



-- 

------------------------------
This message and its contents, including attachments are intended solely 
for the original recipient. If you are not the intended recipient or have 
received this message in error, please notify me immediately and delete 
this message from your computer system. Any unauthorized use or 
distribution is prohibited. Please consider the environment before printing 
this email.

**Comment by litvinen** [comment]
Thanks,
Probably you mean
-db True -mimc_verbose True 
Should I add something like 
> LOG.txt
?

**Comment by haji-ali** [comment]
It outputs to the std output. You can save it by adding ' > LOG.txt ' at
the end of the command.

On Sat, Jun 11, 2016 at 9:28 PM, Alexander Litvinenko <
notifications@github.com> wrote:

> Thanks,
> Probably you mean
> -db True -mimc_verbose True
> Should I add something like
>
> LOG.txt
> ?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/StochasticNumerics/mimclib/issues/49#issuecomment-225381985>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AQb4EJG2Acoq2h_mDu2uYdDEf6zRpOw0ks5qKv5mgaJpZM4IkYpm>
> .
>

-- 

------------------------------
This message and its contents, including attachments are intended solely 
for the original recipient. If you are not the intended recipient or have 
received this message in error, please notify me immediately and delete 
this message from your computer system. Any unauthorized use or 
distribution is prohibited. Please consider the environment before printing 
this email.

**Comment by litvinen** [comment]
I added "> LOG.txt" , but the LOG file is still empty...
Is this part correct?
base = "-u run.py -mimc_TOL {TOL} -mimc_max_TOL 3.0  \
-qoi_seed {seed}  -mimc_M0 3 -mimc_moments 4 \
-mimc_dim 1 -mimc_w 2 -mimc_s 4 -mimc_gamma 3.7 -mimc_beta 2 \
-mimc_bayesian {bayesian}"

cmd_multi = "python " + base + "-mimc_verbose True -db True -db_tag {tag} " + " -db_host {} ".format(args.db_host)
cmd_single = "python " + base + " -mimc_verbose True -db False > 111.txt"

and run like this
 ./echo_test_cmd_alex.py -multi True | parallel -j15 > LOG.txt

**Comment by Virtakuono** [comment]
For anyone looking for stuff relating to the title of this issue, see the following as well:
https://github.com/StochasticNumerics/mimclib/issues/54#issuecomment-252482912
