### ISSUE TITLE
How to see intermediate results?

### ISSUE THREAD

**Issue by litvinen** [StochasticNumerics/mimclib#59]
Assume I run
./echo_test_my.py -tries 18 -multi True | parallel -j18
In previous version I was able to see intermediate results for some large TOL (both in table vw_runs and I could create an intermediate  graphic) and if I didn't like them, I could terminate the MLMC code. 
Now, in the new version, it seems I can see only the final result. Correct?
How to see intermediate results, for instance,  for largest TOL?

**Comment by haji-ali** [comment]
You should be able to see the intermediate results too.

**Comment by litvinen** [comment]
Yes, I see. The structure of tables changed since last version.
My advice is to install GUI Valentina Studio and see all tables there.
