### ISSUE TITLE
Do not understand results. Why so long?

### ISSUE THREAD

**Issue by litvinen** [StochasticNumerics/mimclib#66]
Why it take so long?
I have very large TOL=2.468, very small BIAS=0.0792 and STAT_ERROR=0.139,
why it computes 17967 sec=5 hours? Perturbations are very smooth.

mysql> select * from vw_iters where run_id=208;
 iter_id | run_id | TOL   | creation_date            | bias     | stat_error     | totalTime  
     243 |    208 | 2.468 | 2016-10-11 22:10:22 | 0.0792 | 0.1393         | 17967.48

**Comment by haji-ali** [comment]
Run with verbose output and post the results. Otherwise I have no way of helping

**Comment by litvinen** [comment]
Probably it was connected with my another error. The code was not parallel (I forgot to send the seed from python to my c-code)
