### ISSUE TITLE
No randomness in the solutionm 1.0.2.dev3

### ISSUE THREAD

**Issue by litvinen** [StochasticNumerics/mimclib#67]
I received this output. Why it is always the same numbers? It seems that random generator doesnt work.

Call gr1, n= 642  
Call gr1, n= 642  
Call gr1, n= 642  

returned value goal1= 8.00579  
Call gr1, n= 642  
returned value goal1= 8.00579  
Call gr1, n= 642  
returned value goal1= 8.00579  
Call gr1, n= 642

**Comment by litvinen** [comment]
Python script is below
#!/usr/bin/python
import numpy as np
import argparse

if __name__ == "__main__":
    parser = argparse.ArgumentParser(add_help=True)
    parser.register('type', 'bool',
                    lambda v: v.lower() in ("yes", "true", "t", "1"))
    parser.add_argument("-tries", type=int, action="store",
                        default=0, help="Number of realizations")
    parser.add_argument("-mimc_min_dim", type=int, action="store",
                        default=1, help="MIMC dim")

    args, unknowns = parser.parse_known_args()

    dim = args.mimc_min_dim
    base = "run.py -mimc_TOL {TOL} -mimc_max_TOL 4  -mimc_min_dim 1 -qoi_seed {seed} \
    -mimc_theta 0.5 -mimc_M0 5 -mimc_h0inv 3 \
    -mimc_w 2 -mimc_s 3 -mimc_gamma 1.3 -mimc_beta 2 \
    -mimc_bayes_fit_lvls 3 -mimc_moments 4 \
    -mimc_bayesian {bayesian} ".format(bayesian="{bayesian}", TOL="{TOL}", seed="{seed}")
    base += " ".join(unknowns)

    if args.tries == 0:
        cmd_single = "python " + base + " -mimc_verbose 10 -db False "
        print(cmd_single.format(seed=0, bayesian=False, TOL=0.001))
    else:
        cmd_multi = "python " + base + " -mimc_verbose 0 -db True -db_tag {tag} "
        TOL = 0.5
        for i in range(0, args.tries):
                print cmd_multi.format(bayesian=False,
                                   tag="CEM12Oct_{}".format(dim), TOL=TOL,
                                   seed=np.random.randint(2**32-1))

**Comment by litvinen** [comment]
Ok, the output is the same because input is the same.
Input
Call gr1, n= 642  , v(1.00715, 0.510956, -0.127565)
Call gr1, n= 642  , v(1.00715, 0.510956, -0.127565)
Call gr1, n= 642  , v(1.00715, 0.510956, -0.127565)
But why input on all three processes is the same?

**Comment by haji-ali** [comment]
are you reseeding the random generator with qoi_seed?

**Comment by litvinen** [comment]
I thin yes, here is my python script again, I have parameter -qoi_seed and its value  {seed}
Please check syntax: 
    dim = args.mimc_min_dim
    base = "run.py -mimc_TOL {TOL} -mimc_max_TOL 4  -mimc_min_dim 1 -qoi_seed {seed} \
    -mimc_theta 0.5 -mimc_M0 5 -mimc_h0inv 3 \
    -mimc_w 2 -mimc_s 3 -mimc_gamma 1.3 -mimc_beta 2 \
    -mimc_bayes_fit_lvls 3 -mimc_moments 4 \
    -mimc_bayesian {bayesian} ".format(bayesian="{bayesian}", TOL="{TOL}", seed="{seed}")
    base += " ".join(unknowns)

    if args.tries == 0:
        cmd_single = "python " + base + " -mimc_verbose 10 -db False "
        print(cmd_single.format(seed=0, bayesian=False, TOL=0.001))
    else:
        cmd_multi = "python " + base + " -mimc_verbose 0 -db True -db_tag {tag} "
        TOL = 0.5
        for i in range(0, args.tries):
                print cmd_multi.format(bayesian=False,
                                   tag="CEM12Oct_{}".format(dim), TOL=TOL,
                                   seed=np.random.randint(2**32-1))

**Comment by litvinen** [comment]
Abdul, see please this small test, seeds are different
kw13919:litvina~/NEWMIMCLIB/mimclib2/tests/CEM> ./echo_test_cmd_new.py -tries 2
python run.py -mimc_TOL 0.5 -mimc_max_TOL 4  -mimc_min_dim 1 -qoi_seed 3766909928     -mimc_theta 0.5 -mimc_M0 5 -mimc_h0inv 3     -mimc_w 2 -mimc_s 3 -mimc_gamma 1.3 -mimc_beta 2     -mimc_bayes_fit_lvls 3 -mimc_moments 4     -mimc_bayesian False  -mimc_verbose 0 -db True -db_tag CEM12Oct_1 
python run.py -mimc_TOL 0.5 -mimc_max_TOL 4  -mimc_min_dim 1 -qoi_seed 3090607201     -mimc_theta 0.5 -mimc_M0 5 -mimc_h0inv 3     -mimc_w 2 -mimc_s 3 -mimc_gamma 1.3 -mimc_beta 2     -mimc_bayes_fit_lvls 3 -mimc_moments 4     -mimc_bayesian False  -mimc_verbose 0 -db True -db_tag CEM12Oct_1 
kw13919:litvina~/NEWMIMCLIB/mimclib2/tests/CEM>

**Comment by haji-ali** [comment]
Dear Alex,
I am sure I explained this to you before. This script (and it's executions) do no include the MLMC simulation. They are simply scripts that generate (in this case 2) shell commands to run the MLMC script called 'run.py'. These two commands are passing two different numbers in '-qoi_seed' for run.py to use as a seed for its random number generator. It is your responsibility as a user of the library to read that number and then seed your random number generator that you use to sample the quantity of interest.

With that being said, I did make sure at some point that your 'run.py' script was passing the seed to your C-code which seeds the random number correctly. So unless you changed run.py (or your underlying C code), the new version of the library should have no effect on this.

**Comment by litvinen** [comment]
Abdul, I think the problem is connected with Petsc. Somehow Petsc also has paralelisation
See the first line how I compile my c-code



kw13919:litvina~/111Hakan/cmlmc2> make
/home/litvina/petsc/arch-linux2-c-debug/bin/mpicc -Wall -Wwrite-strings -Wno-strict-aliasing -Wno-unknown-pragmas -fvisibility=hidden -g3  -shared -o needed_functions.so -fPIC needed_functions.o common.o nmsimplex.o /home/litvina/111Hakan/new_code_Abdulkadir_modular2/fmmmodule.o /home/litvina/111Hakan/new_code_Abdulkadir_modular2/geometrymodule.o /home/litvina/111Hakan/new_code_Abdulkadir_modular2/global_comm.o /home/litvina/111Hakan/new_code_Abdulkadir_modular2/global_com.o /home/litvina/111Hakan/new_code_Abdulkadir_modular2/global_geom.o /home/litvina/111Hakan/new_code_Abdulkadir_modular2/legendreroutines.o /home/litvina/111Hakan/new_code_Abdulkadir_modular2/matvectmodule.o /home/litvina/111Hakan/new_code_Abdulkadir_modular2/memory_est.o /home/litvina/111Hakan/new_code_Abdulkadir_modular2/misc_routines.o /home/litvina/111Hakan/new_code_Abdulkadir_modular2/mpi_nonblock.o /home/litvina/111Hakan/new_code_Abdulkadir_modular2/main_module.o /home/litvina/111Hakan/new_code_Abdulkadir_modular2/quadratures.o /home/litvina/111Hakan/new_code_Abdulkadir_modular2/rhsmodule.o /home/litvina/111Hakan/new_code_Abdulkadir_modular2/sourceintmodule.o /home/litvina/111Hakan/new_code_Abdulkadir_modular2/specfun.o /home/litvina/111Hakan/new_code_Abdulkadir_modular2/testintmodule.o /home/litvina/111Hakan/new_code_Abdulkadir_modular2/tfqmr_parallel.o -Wl,-rpath,/home/litvina/petsc/arch-linux2-c-debug/lib -L/home/litvina/petsc/arch-linux2-c-debug/lib  -lpetsc -Wl,-rpath,/home/litvina/petsc/arch-linux2-c-debug/lib -lflapack -lfblas -lhwloc -lX11 -lssl -lcrypto -lm -Wl,-rpath,/usr/lib/gcc/x86_64-linux-gnu/4.8 -L/usr/lib/gcc/x86_64-linux-gnu/4.8 -Wl,-rpath,/usr/lib/x86_64-linux-gnu -L/usr/lib/x86_64-linux-gnu -Wl,-rpath,/lib/x86_64-linux-gnu -L/lib/x86_64-linux-gnu -lmpichf90 -lgfortran -lm -lgfortran -lm -lquadmath -lm -lmpichcxx -lstdc++ -Wl,-rpath,/home/litvina/petsc/arch-linux2-c-debug/lib -L/home/litvina/petsc/arch-linux2-c-debug/lib -Wl,-rpath,/usr/lib/gcc/x86_64-linux-gnu/4.8 -L/usr/lib/gcc/x86_64-linux-gnu/4.8 -Wl,-rpath,/usr/lib/x86_64-linux-gnu -L/usr/lib/x86_64-linux-gnu -Wl,-rpath,/lib/x86_64-linux-gnu -L/lib/x86_64-linux-gnu -Wl,-rpath,/usr/lib/x86_64-linux-gnu -L/usr/lib/x86_64-linux-gnu -ldl -Wl,-rpath,/home/litvina/petsc/arch-linux2-c-debug/lib -lmpich -lopa -lmpl -lrt -lpthread -lgcc_s -ldl  -llapack -lblas -fopenmp -lfftw3 -lfftw3_mpi 
#/home/litvina/petsc/arch-linux2-c-debug/bin/mpicc -Wall -Wwrite-strings -Wno-strict-aliasing -Wno-unknown-pragmas -fvisibility=hidden -g3  -shared -o needed_functions -fPIC needed_functions.o common.o nmsimplex.o /home/litvina/111Hakan/new_code_Abdulkadir_modular2/fmmmodule.o /home/litvina/111Hakan/new_code_Abdulkadir_modular2/geometrymodule.o /home/litvina/111Hakan/new_code_Abdulkadir_modular2/global_comm.o /home/litvina/111Hakan/new_code_Abdulkadir_modular2/global_com.o /home/litvina/111Hakan/new_code_Abdulkadir_modular2/global_geom.o /home/litvina/111Hakan/new_code_Abdulkadir_modular2/legendreroutines.o /home/litvina/111Hakan/new_code_Abdulkadir_modular2/matvectmodule.o /home/litvina/111Hakan/new_code_Abdulkadir_modular2/memory_est.o /home/litvina/111Hakan/new_code_Abdulkadir_modular2/misc_routines.o /home/litvina/111Hakan/new_code_Abdulkadir_modular2/mpi_nonblock.o /home/litvina/111Hakan/new_code_Abdulkadir_modular2/main_module.o /home/litvina/111Hakan/new_code_Abdulkadir_modular2/quadratures.o /home/litvina/111Hakan/new_code_Abdulkadir_modular2/rhsmodule.o /home/litvina/111Hakan/new_code_Abdulkadir_modular2/sourceintmodule.o /home/litvina/111Hakan/new_code_Abdulkadir_modular2/specfun.o /home/litvina/111Hakan/new_code_Abdulkadir_modular2/testintmodule.o /home/litvina/111Hakan/new_code_Abdulkadir_modular2/tfqmr_parallel.o -Wl,-rpath,/home/litvina/petsc/arch-linux2-c-debug/lib -L/home/litvina/petsc/arch-linux2-c-debug/lib  -lpetsc -Wl,-rpath,/home/litvina/petsc/arch-linux2-c-debug/lib -lflapack -lfblas -lhwloc -lX11 -lssl -lcrypto -lm -Wl,-rpath,/usr/lib/gcc/x86_64-linux-gnu/4.8 -L/usr/lib/gcc/x86_64-linux-gnu/4.8 -Wl,-rpath,/usr/lib/x86_64-linux-gnu -L/usr/lib/x86_64-linux-gnu -Wl,-rpath,/lib/x86_64-linux-gnu -L/lib/x86_64-linux-gnu -lmpichf90 -lgfortran -lm -lgfortran -lm -lquadmath -lm -lmpichcxx -lstdc++ -Wl,-rpath,/home/litvina/petsc/arch-linux2-c-debug/lib -L/home/litvina/petsc/arch-linux2-c-debug/lib -Wl,-rpath,/usr/lib/gcc/x86_64-linux-gnu/4.8 -L/usr/lib/gcc/x86_64-linux-gnu/4.8 -Wl,-rpath,/usr/lib/x86_64-linux-gnu -L/usr/lib/x86_64-linux-gnu -Wl,-rpath,/lib/x86_64-linux-gnu -L/lib/x86_64-linux-gnu -Wl,-rpath,/usr/lib/x86_64-linux-gnu -L/usr/lib/x86_64-linux-gnu -ldl -Wl,-rpath,/home/litvina/petsc/arch-linux2-c-debug/lib -lmpich -lopa -lmpl -lrt -lpthread -lgcc_s -ldl  -llapack -lblas
#gfortran -o needed_functions needed_functions.o common.o nmsimplex.o /home/litvina/111Hakan/new_code_Abdulkadir_modular2/fmmmodule.o /home/litvina/111Hakan/new_code_Abdulkadir_modular2/geometrymodule.o /home/litvina/111Hakan/new_code_Abdulkadir_modular2/global_comm.o /home/litvina/111Hakan/new_code_Abdulkadir_modular2/global_com.o /home/litvina/111Hakan/new_code_Abdulkadir_modular2/global_geom.o /home/litvina/111Hakan/new_code_Abdulkadir_modular2/legendreroutines.o /home/litvina/111Hakan/new_code_Abdulkadir_modular2/matvectmodule.o /home/litvina/111Hakan/new_code_Abdulkadir_modular2/memory_est.o /home/litvina/111Hakan/new_code_Abdulkadir_modular2/misc_routines.o /home/litvina/111Hakan/new_code_Abdulkadir_modular2/mpi_nonblock.o /home/litvina/111Hakan/new_code_Abdulkadir_modular2/main_module.o /home/litvina/111Hakan/new_code_Abdulkadir_modular2/quadratures.o /home/litvina/111Hakan/new_code_Abdulkadir_modular2/rhsmodule.o /home/litvina/111Hakan/new_code_Abdulkadir_modular2/sourceintmodule.o /home/litvina/111Hakan/new_code_Abdulkadir_modular2/specfun.o /home/litvina/111Hakan/new_code_Abdulkadir_modular2/testintmodule.o /home/litvina/111Hakan/new_code_Abdulkadir_modular2/tfqmr_parallel.o -Wl,-rpath,/home/litvina/petsc/arch-linux2-c-debug/lib -L/home/litvina/petsc/arch-linux2-c-debug/lib  -lpetsc -Wl,-rpath,/home/litvina/petsc/arch-linux2-c-debug/lib -lflapack -lfblas -lhwloc -lX11 -lssl -lcrypto -lm -Wl,-rpath,/usr/lib/gcc/x86_64-linux-gnu/4.8 -L/usr/lib/gcc/x86_64-linux-gnu/4.8 -Wl,-rpath,/usr/lib/x86_64-linux-gnu -L/usr/lib/x86_64-linux-gnu -Wl,-rpath,/lib/x86_64-linux-gnu -L/lib/x86_64-linux-gnu -lmpichf90 -lgfortran -lm -lgfortran -lm -lquadmath -lm -lmpichcxx -lstdc++ -Wl,-rpath,/home/litvina/petsc/arch-linux2-c-debug/lib -L/home/litvina/petsc/arch-linux2-c-debug/lib -Wl,-rpath,/usr/lib/gcc/x86_64-linux-gnu/4.8 -L/usr/lib/gcc/x86_64-linux-gnu/4.8 -Wl,-rpath,/usr/lib/x86_64-linux-gnu -L/usr/lib/x86_64-linux-gnu -Wl,-rpath,/lib/x86_64-linux-gnu -L/lib/x86_64-linux-gnu -Wl,-rpath,/usr/lib/x86_64-linux-gnu -L/usr/lib/x86_64-linux-gnu -ldl -Wl,-rpath,/home/litvina/petsc/arch-linux2-c-debug/lib -lmpich -lopa -lmpl -lrt -lpthread -lgcc_s -ldl  -llapack -lblas
kw13919:litvina~/111Hakan/cmlmc2>

**Comment by haji-ali** [comment]
Do you actually use petsc?
If you are parallelizing the simulations you have to make sure that the random numbers are generated correctly in each processor.

**Comment by litvinen** [comment]
Thanks Abdul,
You are right, I forgot to send the seed to my c-code

By mistake, from moving from one version to another I changed the run.py script

WRONG
if __name__ == "__main__":
    import mimclib.test
    mimclib.test.RunStandardTest(fnSampleLvl=mySampleLvl,
                                 fnAddExtraArgs=None)

CORRECT
if __name__ == "__main__":
    import mimclib.test
    mimclib.test.RunStandardTest(fnSampleLvl=mySampleLvl,
                                 fnAddExtraArgs=None, fnSeed=seedRandomGen)

**Comment by litvinen** [comment]
Now input uncertainties on each core are different.
Thank you.

**Comment by litvinen** [comment]
>Do you actually use petsc?
I do not need Petsc, but one of your previous version used it, and I didnt cleaned the make file after I moved to the version of MLMC. 
I ask you, do your MLMC neeed Petsc?
 
>If you are parallelizing the simulations you have to make sure that the random numbers are >generated correctly in each processor.
Ok

**Comment by haji-ali** [comment]
That was long ago with CMLMC library. mimclib does not use petsc.
