### ISSUE TITLE
Can the mean on level 0|3 be larger as on level 0|1 ?

### ISSUE THREAD

**Issue by litvinen** [StochasticNumerics/mimclib#71]
Can it be?
0|3  El=0.12  Vl=0.16  
0|1  El=0.07  Vl=0.05 ?

PS : (El on level zero is 6.25, Vl=0.12, the QoI=9)

**Comment by haji-ali** [comment]
Usually not. It is a sign that the coarsest discretization is not sufficient.
However, the worrying factor is not El but Vl. Because that means MLMC might be actually worse than plain Monte Carlo in this case.
