### ISSUE TITLE
Is the make in single run example necessary?

### ISSUE THREAD

**Issue by Virtakuono** [StochasticNumerics/mimclib#72]
I get a warning message "nothing to be done to all" when running the gbm single run example...

Should I just remove the make from https://github.com/StochasticNumerics/mimclib/blob/master/tests/gbm/single_run_example#L5 or is it needed???

**Comment by haji-ali** [comment]
It is needed for a fast run of the GBM example. 
If you make command: "make -q" then it won't output that error message (or any messages for that matter).

**Comment by Virtakuono** [comment]
the -q flag is now added, closing
