### ISSUE TITLE
Problem with tests/gbm/parallel_run_example

### ISSUE THREAD

**Issue by Virtakuono** [StochasticNumerics/mimclib#73]
As I try to run this script, I get:

sqlite3.OperationalError: unable to open database file

I believe I have sqlite installed, I wonder if I need to do something to generate the database file before starting to use it.

**Comment by Virtakuono** [comment]
Looking at https://github.com/StochasticNumerics/mimclib/issues/54#issuecomment-252482912 I am led to believe that the relevant tags are included in the variable COMMON at https://github.com/StochasticNumerics/mimclib/blob/master/tests/gbm/parallel_run_example#L30

**Comment by Virtakuono** [comment]
It appears that the problem is resolved by setting the path in COMMON variable in the existing folder. Perhaps we need change the variable COMMON, or pre-create the file ../db/misc into the repository?

**Comment by haji-ali** [comment]
Yes. You can do either and commit the change.
