### ISSUE TITLE
What is parameter beta if I have a "wild"hierarchy of meshes?

### ISSUE THREAD

**Issue by litvinen** [StochasticNumerics/mimclib#74]
Assume I have grids with N, 2N, 4N, 8N, 16N nodes. In this case beta=2.0
But what if, say mesh with 4N is poor and I exclude it. So, I have only  meshes
N, 2N, 8N, 16N. What is beta?

And general question
I have meshes with N, 1.3N, 1.78N, 2.9N, 3.3N, 4N. What is beta? Can I still use MIMCLIB?

**Comment by Virtakuono** [comment]
If your solver has a given rate, that rate should not change if you change your mind and skip over one or two meshes, no?
