### ISSUE TITLE
Problem with plot.py, KeyError='fnNorm'

### ISSUE THREAD

**Issue by hammouc** [StochasticNumerics/mimclib#75]
I am testing the new version of mimclib in my research application and I have successfully run the single and parallel runs. When plotting results, I am using run_program method so I obtained the plots. Now if I want to have a specific plot from one of the methods in plot.py, let say plotErrorsVsTOL(ax,runs) then I got the following error

File "/home/hammouc/Documents/mimclib-last/mimclib/plot.py", line 243, in plotErrorsVsTOL
    fnNorm = kwargs.pop('fnNorm')
KeyError: 'fnNorm'

Do I need to pass a value for the key 'fnNorm' when calling? if yes fnNorm refers to some norm to work with?  Or something else to fix?? Thanks.

**Comment by haji-ali** [comment]
Yes, you need to pass fnNorm. I should give it a default value to avoid this error, but for now just pass: 'fnNorm=np.abs'

**Comment by hammouc** [comment]
Thank you Abdul for answering. I think it would be helpful to either add a default value for also the other arguments in kwargs or at least to write the nature of the argument so we choose it correctly because sometimes it is not clear. Thank you.

**Comment by hammouc** [comment]
I will be grateful if someone write a brief comment on the meaning of arguments set in kwargs, in particular those not set to default value in plot.py. Thank you for your help.
