### ISSUE TITLE
List of new libraries needed

### ISSUE THREAD

**Issue by Virtakuono** [StochasticNumerics/mimclib#77]
This falls to the general rubrik of README.md being way out of date. First thing I can think of is the dill library, if something else needs to be added to dependencies, please comment here and I'll update the dependency part of README.md in a few days.

**Comment by Virtakuono** [comment]
Sorry for the spam abdo, I assigned to you by mistake.

**Comment by litvinen** [comment]
Very good point @Virtakuono.
I have a lot of difficulties with this help hint from MIMCLIB github page:
"Install Dependencies: python-pip mysql-server mysql-client libmysqlclient-dev build-essential ipython libpng-dev libfreetype6-dev libxft-dev libpython-dev liblapack-dev libblas-dev gfortran parallel numpy matplotlib scipy mysql-python (Package names may be slightly different in your particular platform)"

A lot of packages have different names on Ubuntu, e.g. "mysql-python"

**Comment by Virtakuono** [comment]
Yes, that's why I included the notice that the package names might be a bit different. I cannot cover every architecture, some people do homebrew, some aptitude, some I don't know what. You are welcome to make a comprehensive list with ubuntu, that is very much appreciated.

**Comment by beckjh** [comment]
On OS X Yosemite I am using the following packages (among others):
MySQL 5.6.30

Python 2.7.10 with pip install for packages:
Numpy 1.11.1
Scipy 0.17.1
Matplotlib 1.5.1
MySQL-python 1.2.5
Parallel 0.2.5

To check your own versions you can use, for example: pip freeze | grep matplotlib . Also keep track what python path and mysql path you are using with the following terminal command: which python, and which mysql.

**Comment by beckjh** [comment]
If you get the error below 

RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility

it could be that you need to install scikit-learn or update scipy:

pip uninstall -y scipy scikit-learn
pip install --no-use-wheel scipy scikit-learn

I have version scipy-0.18.1 and scikit-learn 0.18

**Comment by litvinen** [comment]
Ubuntu 14.04 LTS
Python 2.7.12 :: Anaconda 2.4.0 (64-bit)
pip 8.1.2 from /home/litvina/anaconda2/lib/python2.7/site-packages (python 2.7)
Numpy==1.11.2
Scipy==0.17.0
Matplotlib==1.5.1
~> which mysql
/usr/bin/mysql
~> which python
/home/litvina/anaconda2/bin/python

**Comment by Virtakuono** [comment]
Updated readme in e4169ab53a629f737f142890765536cc4c80ce5f, closing
