### ISSUE TITLE
How to run MIMcliib on few separate computers

### ISSUE THREAD

**Issue by litvinen** [StochasticNumerics/mimclib#81]
Assume I have a second computer. I installed MIMCLIB on it.  I run MIMCLIB, all results will be written to the second database. How to tell to the code to write everything to the first database, which is on first computer?
Please write also syntax. Or add one example with IP1 and IP2

**Comment by Virtakuono** [comment]
I believe the solution is ont he parameter here https://github.com/StochasticNumerics/mimclib/blob/master/mimclib/db.py#L46 @haji-ali probably knows which keyword arguments are needed but here is a good start http://mysql-python.sourceforge.net/MySQLdb.html this should work if you have a mysql server running on your machine

**Comment by haji-ali** [comment]
If you are using the test module (i.e. calling RunStandardTest) then all you have to do is pass
-db_host IP
to your run script, where IP is the IP address of the computer that has the database server. This assumes that the user has access to the database.
