### ISSUE TITLE
Very strange (large) time in column tT (tbl_lvls)

### ISSUE THREAD

**Issue by litvinen** [StochasticNumerics/mimclib#88]
Dear Abdul,
In the column tbl_lvls.tT  I see very large numbers, e.g., 111103 sec. and this is for levels 0|1 (iter id=639)

For this level I use relative coarse meshes with 1200 nodes. It should take max 10 minutes!
It could be the case is Ml would be large. But Ml=7. 
For Ml=7 I expect to see maximum 1 hour (4K  sec.), but not 100K.

Can you please check pictures below. See ow huge are tT!

![screenshot from 2016-10-31 08 35 58](https://cloud.githubusercontent.com/assets/430805/19845163/206ef658-9f45-11e6-8caf-eb0cbafc22bd.png)
![screenshot from 2016-10-31 08 36 08](https://cloud.githubusercontent.com/assets/430805/19845162/206d4060-9f45-11e6-90f3-bd3027065fd8.png)

**Comment by haji-ali** [comment]
The time tT is the totalTime (that is: time per sample times the number of samples)

**Comment by litvinen** [comment]
Yes, I understand. I just surprised that tT is so large, 91278 sec. for level 1.

**Comment by haji-ali** [comment]
The variance on level 0 is better than level 1. That's what you should be worried about.
For tT, again, divide by number of samples to get a fair comparison between levels.

**Comment by litvinen** [comment]
@haji-ali >The variance on level 0 is better than level 1. That's what you should be worried about.
Yes, I worry a lot about it. I observed many times that the mean El on level 1 is smaller as on level 2. I am almost sure that this is not a bug, but kind of aliasing (FFT) when I generate random perturbations on the sphere. Any ideas how to generate "better" input uncertainty ?

**Comment by haji-ali** [comment]
This really depends on the problem and I cannot possible give you advice without more understanding of the underlying model. In any case, this is not related to mimclib.
