### ISSUE TITLE
Very high total execution time, what is the reason? 

### ISSUE THREAD

**Issue by litvinen** [StochasticNumerics/mimclib#89]
Dear colleagues,
I received a deterministic code from colleagues. I embedded it into MIMCLIB, but the total running time is very high. I have suspicion that such parts of the deterministic code may be a reason
 if (myid == main_id) then
     print*,'All scattering cross section ::', scs_all
  end if 
This det. code creates a very detailed LOG file. Could it be a reason? Of course the output time itself is small (compare to the computational time of the solver), but  it could be some conflicts when 2 processes are trying to write into one LOG file. But from another hand we have "if (myid == main_id) "...
Any ideas?

**Comment by haji-ali** [comment]
Please restrict all questions on this forum to mimclib.

**Comment by litvinen** [comment]
I think it is a good idea to formulate a best practice guide how to prepare the given deterministic code for embedding into MLMC framework.
@haji-ali ,see, if the deterministic code is not properly prepared, users will say: "MLMC doesnt really work, it is working during  5 days and then I should interrupt it."
