### ISSUE TITLE
What are the optimal compiler options?

### ISSUE THREAD

**Issue by litvinen** [StochasticNumerics/mimclib#90]
It is not a secret that correct compiler options can reduce the computing time drastically.
Can someone share his experience how to get the fastest compiled code? (for mpirun -np my.exe)
I know only option "-g", which allows us debugging and which slow down the whole computational process. So, remove it.
Any others?

**Comment by litvinen** [comment]
Generate optimized code on a Solaris machine using Sun's own CC compiler. This code will generally be faster than g++ optimized code.

```
CC -fast myprog.C -o myprog
```

Generate optimized code on a Linux machine.

```
g++ -O myprog.C -o myprog
```

Option -O3
Optimize yet more. -O3 turns on all optimizations specified by -O2 and also turns on the -finline-functions, -funswitch-loops, -fpredictive-commoning, -fgcse-after-reload, -ftree-loop-vectorize, -ftree-loop-distribute-patterns, -fsplit-paths -ftree-slp-vectorize, -fvect-cost-model, -ftree-partial-pre, -fpeel-loops and -fipa-cp-clone options.

**Comment by Virtakuono** [comment]
It's my understanding that the die hard optimizers do stuff with in-line asm ;)

**Comment by Virtakuono** [comment]
In all seriousness, I think the literature on how to optimize compilation is both broad and deep and I don't think it makes much sense to open the discussion here, as almost everything depends on your problem, your architecture and your compiler.

Feel free to use the standard O-tags if you are using gcc, but beyond that, I think this topic is tangential to the mimclib...

**Comment by litvinen** [comment]
I am disagree. My fortran colleagues do not care about optimisation, memory deallocation etc . They have only one single run, memory will be deallocated automatically when program will be finished, the computing time is not so crucial (12 sec or 20 sec., who cares?). But everything changes when you need to run 10000 runs.
A badly chosen gcc options may kill all advantages of MLMC.

**Comment by Virtakuono** [comment]
No. They may not, if you are honest with yourself, and satisfy some basic regularity assumptions, MLMC **always** outperforms the naive MC. No matter what your compiler options are. It is true that compiler options are relevant, but one of the main points of MIMC is that it is nonintrusive and does not take a stance towards things such as your compiler options.

I am sure there are splendid platforms for debate about compiler tags, I am sure stackexchange will serve your needs better than anything me or @haji-ali can offer.
