### ISSUE TITLE
I used gcc, now I would like to use icc, what do I need to change?

### ISSUE THREAD

**Issue by litvinen** [StochasticNumerics/mimclib#92]
I recompile my c-code (needed_functions.so) with icc.
When I tried to execute MIMCLIB, I receive this message. Do I need to recompile MIMCLIb wwhen I change compiler? 

kw13919:litvina~/NEWMIMCLIB/mimclib/tests/CEM> python run.py -mimc_TOL 0.001 -mimc_max_TOL 0.6  -mimc_min_dim 1 -qoi_seed 0     -mimc_theta 0.5 -mimc_M0 3 -mimc_h0inv 3     -mimc_w 1 -mimc_s 2 -mimc_gamma 1.3 -mimc_beta 2     -mimc_bayes_fit_lvls 3 -mimc_moments 4     -mimc_bayesian True  -mimc_verbose 10 -db False 
Traceback (most recent call last):
  File "run.py", line 28, in <module>
    __lib__ = npct.load_library("needed_functions.so", __libdir)
  File "/usr/local/lib/python2.7/dist-packages/numpy/ctypeslib.py", line 123, in load_library
    return ctypes.cdll[libpath]
  File "/usr/lib/python2.7/ctypes/__init__.py", line 440, in __getitem__
    return getattr(self, name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 435, in __getattr__
    dll = self._dlltype(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/litvina/NEWMIMCLIB/mimclib/tests/CEM/needed_functions.so: undefined symbol: for_open
kw13919:litvina~/NEWMIMCLIB/mimclib/tests/CEM>

**Comment by haji-ali** [comment]
This is related to your module, not mimclib. You have to make sure that the symbols are exported correctly.

**Comment by litvinen** [comment]
Yes, you are right, when I change compiler, the name of the exported module is also changing. Was my issue, not MIMCLIB.
I fixed it. But the I received the next one
I changes everything in my code for icc.

module purge
module load ifort/11.1.075
module load icc/11.1.075
module load mpi-openmpi/1.4.3-icc-11.1
Then in my makefile
F77=mpif77
F90=mpif90

F90FLAGS= -fast -xHost -auto -no-ftz 
F77FLAGS= -fast -xHost -auto -no-ftz

FFTW_LIB=/opt/share/fftw3/3.3-openmpi-1.4.3-generic-dp/el6/x86_64/lib64/
LIB_FFTW=-L${FFTW_LIB} -lfftw3 -lm
LIBS =  ${LIB_FFTW} 

F90SR=global_com.f90 global_geom.f90 quadratures.f90 sourceintmodule.f90 misc_routines.f90 geometrymodule.f90 global_comm.f90 memory_est.f90 fmmmodule.f90 rhsmodule.f90 testintmodule.f90 mpi_nonblock.f90 matvectmodule.f90 legendreroutines.f90 tfqmr_parallel.f90 main_module.f90 main_prog_call_providing.f90
PIM= specfun.f
.f90.o: 
    $(F90) $(F90FLAGS) -c $<
.f.o:
    $(F77) $(F77FLAGS) -c $<
fmmexe: $(ITER) $(MOT)
    $(F90) $(ITER) $(MOT) $(LIBS) -o $@ 

Then I call MIMCLIB
 I obtain this message
kw1391:l~/NEWMIMCLIB/mimclib/tests/CEM> ./echo_test_cmd_new.py -tries 20 | parallel -j20
python: symbol lookup error: /opt/share/mpi-openmpi/1.4.3-icc-11.1/el6/x86_64/lib/openmpi/mca_paffinity_linux.so: undefined symbol: mca_base_param_reg_int
python: symbol lookup error: /opt/share/mpi-openmpi/1.4.3-icc-11.1/el6/x86_64/lib/openmpi/mca_paffinity_linux.so: undefined symbol: mca_base_param_reg_int
...
What is wrong?
How to recompile MIMCLIB for Intel cc ?

**Comment by litvinen** [comment]
I have found this, but do not know how to use it
http://fishercat.sr.unh.edu/trac/mrc-v3/ticket/5

**Comment by haji-ali** [comment]
mimclib does not import mpi, so I am not sure how to help you.
You should debug it a bit more, so I can know which line is responsible for this error.
Does the solution listed on the webpage help?
i.e. adding the following in you mimc_run file

```
from ctypes import *
mpi = CDLL('libmpi.so.0', RTLD_GLOBAL)
```

**Comment by litvinen** [comment]
Problem is fixed by adding this lines to run.py
    try: libmpi = ct.CDLL('libmpi.so', ct.RTLD_GLOBAL)
    except: pass

**Comment by litvinen** [comment]
@haji-ali haj, I posted my\* (thanks to Lissandro) solution before I saw your hint. You are right. Thank you very much.
